language: java
jdk:
    - openjdk8
branches:
    only:
        - master
        
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'
before_install:
    - chmod +x ./gradlew
script: "./gradlew clean build"


before_deploy:
    # 현재 위치의 모든 파일을 springboot-webservice 이름으로 압축
    #- zip -r springboot-webservice *
    # Travis CI 실행되는 위치에 deploy 디렉터리를 생성
    #- mkdir -p deploy
    # 압축 파일을 deploy 디렉터리로 이동
    #- mv springboot-webservice.zip deploy/springboot-webservice.zip
    
    #before-deploy는 배포 파일만 선별
    - mkdir -p before-deploy
    - cp scripts/*.sh before-deploy/
    - cp appspec.yml before-deploy/
    - cp build/libs/*.war before-deploy/
    
    - cd before-deploy && zip -r before-deploy *
    
    - cd .. && mkdir -p deploy
    - mv before-deploy/before-deploy.zip deploy/springboot-webservice.zip

deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $ACCESS_SECRET_KEY
      bucket: a2student10-springboot-webservice
      region: ap-southeast-2
      skip_cleanup: true
      acl: private
      local_dir: deploy
      wait-until-deployed: true
      
    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $ACCESS_SECRET_KEY
      bucket: a2student10-springboot-webservice
      key: springboot-webservice.zip
      bundle_type: zip
      application: springboot-webservice
      deployment_group: springboot-webservice-group
      region: ap-southeast-2
      wait-until-deployed: true
      
notification:
    email:
        recipients:
            - charmce101@gmail.com