version: 0.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/app/step3/zip/
      overwrite: yes

permissions:
    - object: /
      pattern: "**"
      owner: ec2-user
      group: ec2-user
      
hooks:
    ApplicationStart:
        - location: stop.sh
          timeout: 150
          runas: ec2-user
    ApplicationStart:
        - location: start.sh
          timeout: 150
          runas: ec2-user
    ValdiateService:
        - location: health.sh
          timeout: 150
          runas: ec2-user